### ISSUE TITLE
Use Eval Step to Update Experiment Statistics

### ISSUE THREAD

**Issue by jisantuc** [raster-foundry/raster-vision-plugin#8]
@Lknechtli commented on [Mon May 20 2019](https://github.com/raster-foundry/vision-app/issues/202)

What title says.
This will probably require digging a bit into how raster-vision does stuff.

**Comment by notthatbreezy** [comment]
After discussion with @lossyrob there seems to be a way to do this in the eval step that the plugin will have to override.

**Comment by jisantuc** [comment]
Evaluators can be specified in the experiment config -- https://github.com/azavea/raster-vision/blob/master/rastervision/experiment/experiment_config.py#L356-L360

This will also require a `VisionExperimentObjectDetectionEvaluator`, with a config / builder, and that gets registered like the other plugin classes
